---
- name: Create Cachet Monitor directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    setype: container_file_t
  loop:
    - "{{ cachet_monitor_base_dir }}"

- name: Copy Cachet Monitor config file
  ansible.builtin.template:
    src: cachet-monitor.conf.j2
    dest: "{{ cachet_monitor_base_dir }}/cachet-monitor.conf"
    mode: '0644'
  notify: Restart Cachet Monitor

- name: Copy systemd service file for Cachet Monitor
  ansible.builtin.template:
    src: cachet-monitor.container.j2
    dest: /etc/containers/systemd/{{ cachet_monitor_service_name }}.container
    mode: '0644'

- name: Reload systemd to apply new service
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable and start Cachet Monitor service
  ansible.builtin.systemd:
    name: "{{ cachet_monitor_service_name }}"
    enabled: true
    state: started
