---
- name: Update all packages
  ansible.builtin.yum:
    name: '*'
    state: latest

- name: Check if a reboot is required
  ansible.builtin.command:
    cmd: needs-restarting -r
  register: reboot_check
  changed_when: false
  failed_when:
    - reboot_check.rc != 0
    - reboot_check.rc != 1
