---
- name: Update all packages
  ansible.builtin.yum:
    name: '*'
    state: latest
  register: update_result

- name: Reboot the system if needed
  ansible.builtin.reboot:
    reboot_timeout: 3600
  when:
    - update_result.changed
    - ansible_product_name != 'KVM'

- name: Wait for the system to come back online
  ansible.builtin.wait_for_connection:
    timeout: 300
  when:
    - update_result.changed
    - ansible_product_name != 'KVM'
