---
- name: ensure rsyslog is installed
  package: name=rsyslog state=present

- name: start and enable rsyslog
  systemd:
    name: rsyslog
    state: started
    enabled: true

- name: Configure rsyslog client
  include_tasks: configure_client.yml
  when: is_rsyslog_server is undefined

- name: Configure rsyslog server
  include_tasks: configure_server.yml
  when: is_rsyslog_server
