- hosts: oscp-gluster
  user: root
  gather_facts: no
  vars:
     logical_volume_name: "oscp_volume-{{ oscp_project | mandatory }}"
     gluster_volume_name: "oscp_{{ oscp_project | mandatory }}"
  tasks:
    - name: "Create a logical volume of {{ logical_volume_size | mandatory }} MB"
      lvol:
        vg: "{{ volume_group_name }}"
        lv: "{{ logical_volume_name }}"
        size: "{{ logical_volume_size | mandatory }}"

    - name: "Create an xfs filesystem on /dev/{{ volume_group_name }}/{{ logical_volume_name }}"
      filesystem:
        fstype: xfs
        dev: "/dev/{{ volume_group_name }}/{{ logical_volume_name }}"

    - name: Create the glusterfs mount point
      file:
        path: "/mnt/gluster_volumes/{{ gluster_volume_name }}"
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: "Mount /dev/{{ volume_group_name }}/{{ logical_volume_name }}"
      mount:
        path: "/mnt/gluster_volumes/{{ gluster_volume_name }}"
        src: "/dev/{{ volume_group_name }}/{{ logical_volume_name }}"
        fstype: xfs
        opts: noatime
        state: mounted

    - name: Create the glusterfs data directory
      file:
        path: "/mnt/gluster_volumes/{{ gluster_volume_name }}/data"
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: "Create Gluster volume named {{ gluster_volume_name }}"
      gluster_volume:
        state: present
        name: "{{ gluster_volume_name }}"
        bricks: "/mnt/gluster_volumes/{{ gluster_volume_name }}/data"
        replicas: 3
        arbiters: 1
        cluster:
          - 172.31.2.1
          - 172.31.2.2
          - 172.31.2.21
      run_once: true

    - name: "Start gluster volume {{ gluster_volume_name }}"
      gluster_volume:
        state: started
        name: "{{ gluster_volume_name }}"
