---
- name: chrony
  src: https://github.com/openstack/ansible-role-chrony.git
  version: 0111661102ebb211ce8e1a08df57fb51cb4671fb
  scm: git

- name: postfix
  src: https://github.com/linux-system-roles/postfix
  scm: git

- geerlingguy.nodejs
- geerlingguy.docker

