---
- name: Enable EPEL 8
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm"
    state: present

- name: Drop repos we don't want on our systems
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/yum.repos.d/epel-testing.repo
    - /etc/yum.repos.d/epel-playground.repo
    - /etc/yum.repos.d/epel-testing-modular.repo

- name: Install the default set of packages we need
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - net-tools
    - policycoreutils-python-utils
    - setools-console
    - tmux
