---
- name: Create Promtail directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    setype: container_file_t
  loop: "{{ promtail_storage_dirs }}"

- name: Copy Promtail configuration file
  ansible.builtin.template:
    src: promtail-config.yaml.j2
    setype: container_file_t
    dest: "{{ promtail_base_dir }}/config/promtail-config.yaml"
    mode: '0644'

- name: Copy systemd service file for Promtail
  ansible.builtin.template:
    src: promtail.service.j2
    dest: /etc/systemd/system/{{ promtail_service_name }}.service
    mode: '0644'

- name: Reload systemd to apply new service
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable and start Loki service
  ansible.builtin.systemd:
    name: "{{ promtail_service_name }}"
    enabled: true
    state: started
