---
- name: install haproxy and keepalived
  yum: name=haproxy,keepalived

- name: allow haproxy to connect to all TCP ports
  seboolean:
    name: haproxy_connect_any
    state: yes
    persistent: yes

- name: configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: reload haproxy

- name: start and enable haproxy
  systemd:
    name: haproxy
    daemon-reload: yes
    state: started
    enabled: yes

- name: configure keepalived
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  notify: reload keepalived

- name: start and enable keepalived
  systemd:
    name: keepalived
    daemon-reload: yes
    state: started
    enabled: yes
