---
- name: enable pgpool-II repo
  copy:
    src: pgdg.repo
    dest: /etc/yum.repos.d/pgdg.repo

- name: add pgpool-II repo key
  rpm_key:
    state: present
    key: https://download.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG-12

- name: install packages
  yum: name=haproxy,keepalived,pgpool-II-12

- name: allow haproxy to connect to all TCP ports
  seboolean:
    name: haproxy_connect_any
    state: yes
    persistent: yes

- name: configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: reload haproxy

- name: start and enable haproxy
  systemd:
    name: haproxy
    daemon-reload: yes
    state: started
    enabled: yes

- name: configure keepalived
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  notify: reload keepalived

- name: start and enable keepalived
  systemd:
    name: keepalived
    daemon-reload: yes
    state: started
    enabled: yes

- name: configure pgpool
  template:
    src: pgpool.conf.j2
    dest: /etc/pgpool-II-12/pgpool.conf
  notify: reload pgpool

- name: start and enable pgpool-II-12
  systemd:
    name: pgpool-II-12
    daemon-reload: yes
    state: started
    enabled: yes
