---
- name: restart gitlab-runner
  service: name=gitlab-runner state=restarted

- name: daemon reload
  systemd: daemon_reload=yes

- name: reload sysctl
  command: sysctl --system --load

- name: restart docker
  service: name=docker.service state=restarted

- name: reload udevadm
  command: udevadm control --reload-rules
