---
- name: restart gitlab-runner
  ansible.builtin.systemd:
    name: gitlab-runner.service
    state: restarted
    daemon_reload: true
    scope: user
  become_user: podman

- name: restart pydocuum
  ansible.builtin.systemd:
    name: pydocuum.service
    state: restarted
    daemon_reload: true
    scope: user
  become_user: podman

- name: reload udevadm
  ansible.builtin.command: udevadm control --reload-rules

- name: trigger udevadm
  ansible.builtin.command: udevadm trigger

- name: podman system migrate
  ansible.builtin.command: podman system migrate
  become_user: podman
