---
- name: Install and configure sshguard
  block:
    - name: Install sshguard packages
      ansible.builtin.package:
        name:
          - sshguard
          - sshguard-iptables
        state: present

    - name: Configure sshguard and whitelist from templates
      ansible.builtin.template:
        src: "{{ item }}.j2"
        dest: "/etc/{{ item }}"
        owner: root
        group: root
        mode: '0644'
      loop:
        - sshguard.conf
        - sshguard.whitelist
      notify: Restart sshguard service

    - name: Ensure sshguard service is started and enabled on boot
      ansible.builtin.systemd:
        name: sshguard
        state: started
        enabled: true

    - name: Make sure the iptables service is masked
      ansible.builtin.systemd:
        name: iptables
        masked: true
  when: sshguard_enabled | default(false)
