---
- name: allow signal.g.o to access exporters ports
  ufw:
    rule: allow
    proto: tcp
    src: 140.211.167.18/32
    port: "{{ item }}"
    comment: node-exporter
  loop:
    - "9100" # node_exporter
    - "9688" # bbb-exporter

- name: register bbb secret
  command: bbb-conf --secret
  changed_when: false
  register: result
  when: not bbb_secret is defined

- name: parse bbb secret
  set_fact:
    bbb_secret: "{{ result.stdout | regex_search('Secret: ([a-zA-Z0-9]*)', multiline=True) |  regex_replace('Secret: ') }}"
    cacheable: true
  when: not bbb_secret is defined

- name: start bbb_exporter
  docker_container:
    name: bbb_exporter
    image: greenstatic/bigbluebutton-exporter:v0.5.0
    state: present
    restart_policy: unless-stopped
    ports:
      - "9688:9688"
    volumes:
      - /var/bigbluebutton:/var/bigbluebutton:ro
    env:
      RECORDINGS_METRICS_READ_FROM_DISK: "true"
      API_SECRET: "{{ bbb_secret }}"
      API_BASE_URL: https://meet.gnome.org/bigbluebutton/api/

- name: install node-exporter-openvpn-cert-notafter script
  copy:
    src: node-exporter-openvpn-cert-notafter
    dest: /usr/local/bin/node-exporter-openvpn-cert-notafter
    mode: "0755"

- name: install node-exporter-openvpn-cert-notafter systemd unit and timer
  copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
  loop:
    - node-exporter-openvpn-cert-notafter.timer
    - node-exporter-openvpn-cert-notafter.service

- name: enable node-exporter-openvpn-cert-notafter timer
  systemd:
    name: node-exporter-openvpn-cert-notafter.timer
    daemon-reload: yes
    state: started
    enabled: yes
