---
- name: set root ssh keys
  ansible.builtin.copy:
    src: root_authorized_keys
    dest: /root/.ssh/authorized_keys
    owner: root
    group: root
    mode: 0600

- include_tasks: common.yml
  when: ansible_distribution != "NixOS"

- include_tasks: firewalld.yml
  when: skip_firewalld is undefined

- include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- include_tasks: fedora.yml
  when: ansible_distribution == "Fedora"
