---
- name: Restart Postfix
  service: name=postfix state=restarted

- name: Reload Postfix
  service: name=postfix state=reloaded

- name: Postmap virtual aliases file
  command:
    cmd: "/usr/sbin/postmap {{ item.dest }}"
  with_items: "{{ _postfix_postmap_files.results | selectattr('changed', 'equalto', true) | list }}"

- name: Postalias aliases files
  command:
    cmd: "/usr/sbin/postalias {{ item.dest }}"
  with_items: "{{ _postfix_postalias_files.results | selectattr('changed', 'equalto', true) | list }}"

- name: Restart OpenDKIM
  service: name=opendkim state=restarted
