node_exporter_arch_map:
  i386: '386'
  x86_64: 'amd64'
  aarch64: 'arm64'
  armv7l: 'armv7'
  armv6l: 'armv6'

node_exporter_arch: "{{ node_exporter_arch_map[ansible_architecture] | default(ansible_architecture) }}"

node_exporter_old_service: "{{ (ansible_os_family == 'Debian') | ternary('prometheus-node-exporter.service', 'node_exporter.service') }}"
node_exporter_old_package: "{{ (ansible_os_family == 'Debian') | ternary('prometheus-node-exporter', 'golang-github-prometheus-node_exporter') }}"
