- name: include prometheus role
  import_role:
    name: prometheus
    tasks_from: common
  vars:
    prometheus_retention_time: "14d"

- name: configure prometheus
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    force: true
    owner: root
    group: prometheus
    mode: 0640
    validate: "/usr/local/bin/promtool check config %s"
  notify: reload prometheus
  tags: prometheus_config
