---
- name: install fedora packages
  ansible.builtin.package:
    name:
      - dnf-automatic
      - "{{ 'golang-github-prometheus-node-exporter' if ansible_distribution_major_version == '40' else 'node-exporter' }}"
      - vim-minimal
    state: present
    update_cache: true

- name: add tailscale repo
  ansible.builtin.command: >
    dnf config-manager
    {% if ansible_distribution_major_version == '40' %}
    --add-repo
    {% else %}
    addrepo --from-repofile
    {% endif %}
    https://pkgs.tailscale.com/stable/fedora/tailscale.repo
  args:
    creates: /etc/yum.repos.d/tailscale.repo

- name: start and enable services
  ansible.builtin.systemd:
    state: started
    name: "{{ item }}"
    enabled: true
  with_items:
    - dnf-automatic.timer
    - node_exporter

- name: Configure chronyd
  ansible.builtin.include_role:
    name: chrony

- name: Configure dnf-automatic.conf for automatic updates and reboot
  ansible.builtin.lineinfile:
    path: /etc/dnf/automatic.conf
    regexp: "^{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    create: false
  loop:
    - { regexp: 'apply_updates =', line: 'apply_updates = yes' }
    - { regexp: 'reboot =', line: 'reboot = when_needed' }

- name: Create systemd drop-in directory for dnf-automatic.timer
  ansible.builtin.file:
    path: /etc/systemd/system/dnf-automatic.timer.d
    state: directory
    mode: '0755'

- name: Configure dnf-automatic timer to run on Sunday 10 PM EST
  ansible.builtin.copy:
    content: |
      [Timer]
      OnCalendar=Sun *-*-* 22:00
      Persistent=true
    dest: /etc/systemd/system/dnf-automatic.timer.d/override.conf
    mode: '0644'
  notify:
    - Reload systemd daemon
    - Restart dnf-automatic timer
