---
- name: install firewalld
  ansible.builtin.package:
    name:
      - firewalld
    state: present
    update_cache: true

- name: set default firewalld zone to public
  ansible.builtin.command: firewall-cmd --set-default-zone=public
  register: default_zone_set
  changed_when:
    - '"ZONE_ALREADY_SET" not in default_zone_set.stderr'

- name: start and enable firewalld
  ansible.builtin.systemd:
    state: started
    name: firewalld
    enabled: true

- name: add tailscale0 to internal zone
  ansible.posix.firewalld:
    zone: internal
    interface: tailscale0
    permanent: true
    immediate: true
    state: enabled

- name: allow node-exporter access over tailscale
  ansible.posix.firewalld:
    zone: internal
    port: 9100/tcp
    permanent: true
    immediate: true
    state: enabled
