---
- import_tasks: common.yml

- name: configure prometheus
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    force: true
    owner: root
    group: prometheus
    mode: 0640
    validate: "/usr/local/bin/promtool check config %s"
  notify: reload prometheus
  tags: prometheus_config

- name: configure alerting rules
  template:
    src: alerting.rules.j2
    dest: "{{ prometheus_config_dir }}/rules/alerting.rules"
    owner: root
    group: prometheus
    mode: 0640
    validate: "/usr/local/bin/promtool check rules %s"
  notify: reload prometheus
  tags:
    - prometheus_config

- name: Copy over Openshift Monitoring rule file (expr)
  copy:
    src: openshift-monitoring.rules
    dest: "{{ prometheus_config_dir }}/rules/openshift-monitoring.rules"
    owner: root
    group: prometheus
    mode: '0640'
    validate: "/usr/local/bin/promtool check rules %s"
  notify: reload prometheus
  tags:
    - prometheus_config

- name: start and enable prometheus
  systemd:
    name: prometheus
    daemon-reload: yes
    state: started
    enabled: yes
  tags: prometheus_config
