---
- name: set selinux to enforcing
  selinux:
    policy: targeted
    state: enforcing

- name: install python2-dnf
  yum: name=python2-dnf state=present

- name: install docker
  yum: name=docker state=present

- name: Add gitlab-runner repository
  yum_repository:
    name: runner_gitlab-runner
    description: GitLab Runner repository
    file: runner_gitlab-runner
    baseurl: "https://packages.gitlab.com/runner/gitlab-runner/{{ ansible_distribution|lower }}/$releasever/$basearch"
    gpgcheck: no

- name: install selinux-policy-devel
  yum: name=selinux-policy-devel state=present

- name: copy docker_gitlab_runner.te file
  copy:
    src: docker_gitlab_runner.te
    dest: /etc/selinux/targeted/docker_gitlab_runner.te
    mode: 0644
  register: docker_gitlab_runner_te

- name: check for docker_gitlab_runner.pp file
  stat:
    path: /etc/selinux/targeted/docker_gitlab_runner.pp
  register: docker_gitlab_runner_pp_check

- name: compile docker_gitlab_runner selinux module
  command: make -f /usr/share/selinux/devel/Makefile -C /etc/selinux/targeted/ docker_gitlab_runner.pp
  register: docker_gitlab_runner_pp
  when: (docker_gitlab_runner_te is changed) or (not docker_gitlab_runner_pp_check.stat.exists)

- name: install docker_gitlab_runner selinux module
  command: semodule -i /etc/selinux/targeted/docker_gitlab_runner.pp
  when: docker_gitlab_runner_pp is changed

- name: install gitlab-runner
  yum: name=gitlab-runner state=present
