---
- name: add authorized keys for root
  copy: src=authorized_keys dest=/root/.ssh/authorized_keys mode=0600 owner=root group=root

- include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- include_tasks: fedora.yml
  when: ansible_distribution == "Fedora"

- name: configure gitlab-runner
  template:
    src: config.toml.j2
    dest: /etc/gitlab-runner/config.toml
  notify: restart gitlab-runner
