---
- name: include common tasks
  ansible.builtin.include: common.yml
  when: ansible_distribution != "NixOS"

- name: include nixos tasks
  ansible.builtin.include: nixos.yml
  when: ansible_distribution == "NixOS"
