---
- name: add authorized keys for root
  copy: src=authorized_keys dest=/root/.ssh/authorized_keys mode=0600 owner=root group=root

- include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- include_tasks: debian.yml
  when: ansible_distribution == "Debian"

- include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- name: configure docker
  template: src=dockerd.json.j2 dest=/etc/docker/daemon.json
  notify: restart docker
  tags: docker

- name: start and enable docker
  service: name=docker state=started enabled=true
  tags: docker

- name: configure gitlab-runner
  template:
    src: config.toml.j2
    dest: /etc/gitlab-runner/config.toml
  notify: restart gitlab-runner
  tags: gitlab-runner

- name: install seccomp profile for flatpak
  copy: >
    src=files/flatpak-docker-seccomp.json dest=/etc/docker/flatpak.seccomp.json
    owner=root group=root mode=0640

- name: install docker-gc
  copy: >
    src=files/docker-gc/docker-gc dest=/usr/local/bin/docker-gc
    owner=root group=root mode=0700

- name: install docker-gc systemd units
  template: src={{ item }}.j2 dest=/etc/systemd/system/{{ item }}
  with_items:
    - docker-gc.service
    - docker-gc.timer
  notify:
    - daemon reload
    - restart docker-gc timer

- name: start and enable docker-gc timer
  service: name=docker-gc.timer enabled=yes state=started

- name: copy increase-arp-table-size.conf in place
  copy: src=increase-arp-table-size.conf dest=/etc/sysctl.d/increase-arp-table-size.conf mode=0644 owner=root group=root
  notify: reload sysctl
