---
- name: include common tasks
  ansible.builtin.include_tasks: common.yml
  when: ansible_distribution != "NixOS"

- name: include nixos tasks
  ansible.builtin.include_tasks: nixos.yml
  when: ansible_distribution == "NixOS"
