---
- name: copy seccomp profile for building flatpaks
  ansible.builtin.copy:
    src: flatpak.seccomp.json
    dest: /etc/gitlab-runner/flatpak.seccomp.json

- name: configure gitlab-runner
  ansible.builtin.template:
    src: gitlab-runner-config.toml.j2
    dest: /etc/gitlab-runner/config.toml
    mode: '0600'
