---
- name: set selinux to enforcing
  selinux:
    policy: targeted
    state: enforcing

- name: install python2-dnf
  yum: name=python2-dnf state=present

- name: remove CentOS docker packages
  yum: name=docker,docker-common state=absent
  tags: docker

- name: add docker repository
  yum_repository:
    name: docker-ce
    description: Docker CE
    file: docker-ce
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg
    gpgcheck: yes

- name: install docker-ce
  yum: name=docker-ce,docker-ce-cli,containerd.io state=present

- name: add gitlab-runner repository
  yum_repository:
    name: runner_gitlab-runner
    description: GitLab Runner repository
    file: runner_gitlab-runner
    baseurl: https://packages.gitlab.com/runner/gitlab-runner/el/$releasever/$basearch
    gpgcheck: no
  when: ansible_distribution == 'CentOS'

- name: install selinux-policy-devel
  yum: name=selinux-policy-devel state=present

- name: configure selinux modules
  include_tasks: selinux.yml
  loop:
    - docker_gitlab_runner
    - flatpak_builder
  tags: selinux

- name: allow user namespaces
  copy: src=max_user_namespaces.conf dest=/etc/sysctl.d/max_user_namespaces.conf mode=0644 owner=root group=root
  notify: reload sysctl
  tags: selinux

- name: install gitlab-runner
  yum: name=gitlab-runner state=present
