---
- name: add docker repository
  yum_repository:
    name: docker-ce
    description: Docker CE
    file: docker-ce
    baseurl: https://download.docker.com/linux/fedora/$releasever/$basearch/stable
    gpgkey: https://download.docker.com/linux/fedora/gpg
    gpgcheck: yes

- name: install docker
  yum: name=docker-ce,docker-ce-cli,containerd.io,python3-docker,crun state=present

- name: start and enable docker socket
  systemd: name=docker.socket state=started enabled=yes

- name: add gitlab-runner repository
  yum_repository:
    name: runner_gitlab-runner
    description: GitLab Runner repository
    baseurl: https://packages.gitlab.com/runner/gitlab-runner/fedora/33/$basearch
    gpgkey: |
      https://packages.gitlab.com/runner/gitlab-runner/gpgkey
      https://packages.gitlab.com/runner/gitlab-runner/gpgkey/runner-gitlab-runner-4C80FB51394521E9.pub.gpg
    file: runner_gitlab-runner
    gpgcheck: yes

- name: install selinux-policy-devel
  yum: name=selinux-policy-devel state=present

- name: configure selinux modules
  include_tasks: selinux.yml
  loop:
    - docker_gitlab_runner
    - flatpak_builder
  tags: selinux

- name: allow user namespaces
  copy: src=max_user_namespaces.conf dest=/etc/sysctl.d/max_user_namespaces.conf mode=0644 owner=root group=root
  notify: reload sysctl
  tags: selinux

- name: install gitlab-runner
  yum: name=gitlab-runner,cronie state=present
