---
- name: add packagecloud gpg key to apt keyring
  apt_key:
    url: https://packages.gitlab.com/runner/gitlab-runner/gpgkey
    state: present

- name: add gitlab-runner repository
  apt_repository:
    repo: "deb https://packages.gitlab.com/runner/gitlab-runner/ubuntu/ {{ ansible_distribution_release }} main"
    state: present

- name: install docker
  apt:
    name: docker.io
    state: present
    update_cache: yes
    cache_valid_time: 3600
