---
- name: restart prometheus
  systemd:
    name: prometheus
    daemon-reload: yes
    state: restarted

- name: reload prometheus
  systemd:
    name: prometheus
    daemon-reload: yes
    state: reloaded

- name: restart blackbox_exporter
  systemd:
    name: blackbox_exporter
    daemon-reload: yes
    state: restarted
