---
- hosts: meet.gnome.org
  gather_facts: true
  remote_user: root
  roles:
    - bigbluebutton
    - node-exporter

- hosts: fosshost.gnome.org
  gather_facts: true
  remote_user: root
  roles:
    - coturn
