---
- hosts:
  - oscp-nodes
  - meet.gnome.org
  gather_facts: true
  remote_user: root
  tasks:
    - name: install required packages
      package: name=jq,iproute state=present

    - name: create docker volume
      command: docker volume create co2-stats

    - name: install timer
      copy:
        dest: /etc/systemd/system/co2-stats.timer
        content: |
          [Unit]
          Description=Collect carbon emissions statistics

          [Timer]
          OnBootSec=2min
          OnUnitActiveSec=30min

          [Install]
          WantedBy=timers.target

    - name: install service
      copy:
        dest: /etc/systemd/system/co2-stats.service
        content: |
          [Unit]
          Description=Collect carbon emissions statistics
          After=network.target

          [Service]
          Type=oneshot
          ExecStart=/usr/bin/docker run --rm -v co2-stats:/var/log --net host registry.gitlab.gnome.org/infrastructure/oci-images/co2-stats:3

          [Install]
          WantedBy=multi-user.target

    - name: start and enable timer
      systemd:
        name: co2-stats.timer
        daemon-reload: yes
        state: started
        enabled: yes

- hosts:
  - scale.gnome.org
  - gesture.gnome.org
  gather_facts: true
  remote_user: root
  tasks:
    - name: install required packages
      package: name=jq,iproute state=present

    - name: install script
      copy:
        dest: /usr/local/bin/co2-stats
        mode: "0700"
        content: |
          #!/bin/bash
          /bin/bash -c '(date -Iseconds; nproc; cat /proc/loadavg; ifstat --noupdate --ignore | tail -n +4) | jq --slurp --raw-input --compact-output '\''split("\n")[:-1] | map([ split(" ")[] | select(. != "") ]) | {"date": .[0][], "nproc": .[1][], "uptime": .[2], "ifstat": [ .[3:] as $i | range(0; $i | length; 2) | {($i[.][0]): $i[.][1:] }] | add}'\'' >> /var/log/co2-stats.json'

    - name: install timer
      copy:
        dest: /etc/systemd/system/co2-stats.timer
        content: |
          [Unit]
          Description=Collect carbon emissions statistics

          [Timer]
          OnBootSec=2min
          OnUnitActiveSec=30min

          [Install]
          WantedBy=timers.target

    - name: install service
      copy:
        dest: /etc/systemd/system/co2-stats.service
        content: |
          [Unit]
          Description=Collect carbon emissions statistics
          After=network.target

          [Service]
          Type=oneshot
          ExecStart=/usr/local/bin/co2-stats

          [Install]
          WantedBy=multi-user.target

    - name: start and enable timer
      systemd:
        name: co2-stats.timer
        daemon-reload: yes
        state: started
        enabled: yes
