---
- hosts: gitlab-runners
  gather_facts: true
  remote_user: root
  roles:
   - external_base
   - gitlab-runner

- name: gather facts
  hosts: gitlab-runners,external
  remote_user: root
  gather_facts: true
  tasks: []

- hosts: hetzner-3
  gather_facts: true
  remote_user: root
  roles:
   - external_prometheus
