---
- hosts: gitlab-runners
  remote_user: root
  serial: 1
  tasks:
    - name: upgrade
      block:
        - name: install updates
          apt: upgrade=safe update_cache=yes cache_valid_time=3600
          when: ansible_os_family == 'Debian'

        - name: install updates
          yum:
            name: '*'
            state: latest
          when: ansible_os_family == 'RedHat'

        - name: reboot {{ inventory_hostname }}
          reboot:
