---
- hosts: all
  gather_facts: false
  remote_user: root
  collections:
   - community.general
  tasks:
    - name: Register system to RHSM
      community.general.redhat_subscription:
        state: present
        username: "{{ rhsm_username }}"
        password: "{{ rhsm_password }}"
        auto_attach: true

- hosts: all
  gather_facts: true
  remote_user: root
  roles:
   - packages
   - motd
   - chrony
   - iptables
   - postfix.wrapper
   - bash
   - base_auth
   - nrpe
   - base_network
   - rsyslog
   - backup
   - node-exporter
   - ipaclient.wrapper
