---
- hosts: all
  gather_facts: true
  remote_user: root
  roles:
   - community.general.redhat_subscription
   - packages
   - motd
   - chrony
   - iptables
   - ipaclient.wrapper
   - postfix.wrapper
   - bash
   - base_auth
   - nrpe
   - base_network
   - rsyslog

- hosts: hypervisors
  gather_facts: true
  remote_user: root
  roles:
   - dell

- hosts: bastions
  gather_facts: true
  remote_user: root
  roles:
   - squid
   - node-exporter

- hosts: nsd
  gather_facts: true
  remote_user: root
  roles:
   - nsd
   - node-exporter
