---
- hosts: all
  gather_facts: false
  remote_user: root
  collections:
   - community.general
  tasks:
    - name: Register system to RHSM
      community.general.redhat_subscription:
        state: present
        username: "{{ rhsm_username }}"
        password: "{{ rhsm_password }}"
        auto_attach: true

- hosts: all,!ceph,!ceph-metrics.gnome.org
  gather_facts: true
  remote_user: root
  roles:
   - packages
   - motd
   - chrony
   - iptables
   - ipaclient.wrapper
   - postfix.wrapper
   - bash
   - base_auth
   - nrpe
   - base_network
   - rsyslog
   - node-exporter

- hosts: hypervisors
  gather_facts: true
  remote_user: root
  roles:
   - dell

- hosts: bastions
  gather_facts: true
  remote_user: root
  roles:
   - squid

- hosts: nsd
  gather_facts: true
  remote_user: root
  roles:
   - nsd

- hosts: master.gnome.org
  gather_facts: false
  remote_user: root
  roles:
    - ftpadmin
