- hosts: vpnclients
  remote_user: root
  tasks:
    - name: Revoke the existing certificate
      shell: echo -en 'yes' | /etc/openvpn/easy-rsa/easyrsa revoke non-phx2-machines-{{ ansible_hostname }}
      args:
        chdir: /etc/openvpn/easy-rsa
      delegate_to: bastion.gnome.org

    - name: Re-generate the CRL
      command: /etc/openvpn/easy-rsa/easyrsa gen-crl
      args:
        chdir: /etc/openvpn/easy-rsa
      delegate_to: bastion.gnome.org

    - name: Assign the correct set of permissions to the crl.pem file
      file: path=/etc/openvpn/pki/crl.pem mode=0644 owner=root group=root
      delegate_to: bastion.gnome.org

    - name: remove the revoked certs from disk (.crt)
      file: path="/etc/openvpn/easy-rsa/pki/issued/non-phx2-machines-{{ ansible_hostname }}.crt" state=absent
      delegate_to: bastion.gnome.org

    - name: Remove the revoked certs from disk (.key)
      file: path="/etc/openvpn/easy-rsa/pki/private/non-phx2-machines-{{ ansible_hostname }}.key" state=absent
      delegate_to: bastion.gnome.org

    - name: Remove the revoked certs from disk (.req)
      file: path="/etc/openvpn/easy-rsa/pki/reqs/non-phx2-machines-{{ ansible_hostname }}.req" state=absent
      delegate_to: bastion.gnome.org

    - name: Generate a new set of certificates
      command: "/etc/openvpn/easy-rsa/easyrsa build-client-full non-phx2-machines-{{ ansible_hostname }} nopass"
      args:
        chdir: /etc/openvpn/easy-rsa
      delegate_to: bastion.gnome.org

    - name: Clone the certificates repository locally under /tmp/certificates
      git: clone=yes dest=/tmp/certificates repo="ssh://root@puppetmaster01.gnome.org/git/certificates"
      run_once: true
      delegate_to: 127.0.0.1

    - name: Copy the certificates from the OpenVPN server to the local certificates repository clone (.crt)
      fetch: src="/etc/openvpn/easy-rsa/pki/issued/non-phx2-machines-{{ ansible_hostname }}.crt" dest=/tmp/certificates/openvpn/ flat=yes
      delegate_to: bastion.gnome.org

    - name: Copy the certificates from the OpenVPN server to the local certificates repository clone (.key)
      fetch: src="/etc/openvpn/easy-rsa/pki/private/non-phx2-machines-{{ ansible_hostname }}.key" dest=/tmp/certificates/openvpn/ flat=yes
      delegate_to: bastion.gnome.org

    - name: Commit the new certificates!
      command: /usr/bin/git commit -am "Renew VPN Certificates for {{ inventory_hostname }}"
      args:
        chdir: /tmp/certificates
      delegate_to: 127.0.0.1

    - name: Push the new certificates!
      command: /usr/bin/git push
      args:
        chdir: /tmp/certificates
      delegate_to: 127.0.0.1

    - name: Copy the certificates on the target machine (.crt)
      copy: src="/tmp/certificates/openvpn/non-phx2-machines-{{ ansible_hostname }}.crt" dest="/etc/openvpn/keys/non-phx2-machines-{{ ansible_hostname }}.crt" mode=0644 owner=root

    - name: Copy the certificates on the target machine (.key)
      copy: src="/tmp/certificates/openvpn/non-phx2-machines-{{ ansible_hostname }}.key" dest="/etc/openvpn/keys/non-phx2-machines-{{ ansible_hostname }}.key" mode=0600 owner=root

    - name: Restart openvpn client (RHEL 7)
      service: name=openvpn@client state=restarted
      when: (ansible_distribution == "RedHat" and ansible_distribution_major_version >= "7") or
            (ansible_distribution == "CentOS" and ansible_distribution_major_version >= "7") or
            (ansible_distribution == "Ubuntu")

    - name: Restart openvpn client (RHEL 6)
      service: name=openvpn state=restarted
      when: (ansible_distribution == "RedHat" and ansible_distribution_major_version < "7") or
            (ansible_distribution == "CentOS" and ansible_distribution_major_version < "7")

    - name: Remove the /tmp/certificates directory
      file: path=/tmp/certificates state=absent
      delegate_to: 127.0.0.1
