---
- name: Update packages and reboot systems
  hosts: all !idm
  remote_user: root
  roles:
    - package_updates
  tasks:
    - name: Reboot the system if needed
      ansible.builtin.reboot:
        reboot_timeout: 1200
      when:
        - reboot_check.rc == 1

    - name: Wait for the system to come back online
      ansible.builtin.wait_for_connection:
        timeout: 300
      when:
        - reboot_check.rc == 1

- name: Update packages and reboot systems (IDM only)
  hosts: idm
  serial: 1
  remote_user: root
  gather_facts: false
  roles:
    - package_updates
  tasks:
    - name: Reboot the system if needed
      ansible.builtin.reboot:
        reboot_timeout: 1200
      when:
        - reboot_check.rc == 1

    - name: Wait for the system to come back online
      ansible.builtin.wait_for_connection:
        timeout: 300
      when:
        - reboot_check.rc == 1

    - name: Check IDM services status
      ansible.builtin.command:
        cmd: /usr/local/bin/ipa_status.py -v
      register: check_ipa_status
      until: check_ipa_status.stdout.find("OK:") != -1
      retries: 20
      delay: 60
      changed_when: false
