---
- name: Update packages and reboot systems
  hosts: all,!ceph_osds,!hypervisors,!ipaservers
  remote_user: root
  gather_facts: false
  roles:
    - package_updates

- name: Package updates on Ceph nodes
  hosts: ceph_osds
  remote_user: root
  gather_facts: false
  serial: 1
  roles:
    - package_updates
  tasks:
    - name: Select a node for Ceph health check
      ansible.builtin.set_fact:
        delegate_node: "{{ item }}"
      with_items: "{{ groups['ceph_osds'] }}"
      run_once: true
      when:
        - item != inventory_hostname
        - update_result.changed

    - name: Check Ceph health
      ansible.builtin.command:
        cmd: ceph -s -f json
      register: ceph_status
      until: ceph_status.stdout | from_json | json_query('health.status') == "HEALTH_OK"
      retries: 20
      delay: 60
      delegate_to: "{{ delegate_node }}"
      run_once: true
      when: update_result.changed

- name: Package updates on IPA nodes
  hosts: ipaservers
  remote_user: root
  gather_facts: false
  serial: 1
  roles:
    - package_updates
  tasks:
    - name: Let IDM services stabilize
      ansible.builtin.pause:
        minutes: 5
      when: update_result.changed
