---
apiVersion: v1
kind: Service
metadata:
  name: glusterfs-cluster
spec:
  ports:
  - port: 1
---
apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
subsets:
  - addresses:
      - ip: 172.31.2.1
    ports:
      - port: 1
  - addresses:
      - ip: 172.31.2.2
    ports:
      - port: 1
