---
- name: Land custom ldifs
  copy:
    src: "files/{{ item }}"
    dest: /etc/dirsrv/slapd-GNOME-ORG/schema
    owner: dirsrv
    group: dirsrv
    mode: '0440'
  with_items:
    - 96foundation.ldif

- name: Create foundation IDM plugin directory
  file:
    path: /usr/share/ipa/ui/js/plugins/foundation
    state: directory
    mode: '0755'

- name: Land custom foundation IDM plugin
  copy:
    src: files/foundation.js
    dest: /usr/share/ipa/ui/js/plugins/foundation
    owner: root
    group: root
    mode: '0644'
  notify:
    - 'Restart httpd'

- name: Land AWS ELB httpd conf
  template:
    src: templates/aws-elb.conf.j2
    dest: /etc/httpd/conf.d/aws-elb.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - 'Restart httpd'

- name: Include /etc/httpd/conf.d/aws-elb.conf
  lineinfile:
    path: /etc/httpd/conf.d/ssl.conf
    insertafter: '^Include /etc/httpd/conf.d/ipa-rewrite.conf'
    line: 'Include /etc/httpd/conf.d/aws-elb.conf'
    state: present

- name: Ensure ipa is running
  service:
    name: ipa
    enabled: true
    state: started
