---
- name: add certbot PPA
  apt_repository:
    repo: ppa:certbot/certbot
    update_cache: yes

- name: install packages
  package:
    name: coturn,certbot

- name: request ssl certificate
  command: certbot certonly --standalone --preferred-challenges http --agree-tos --rsa-key-size 4096 --renew-by-default -d '{{ coturn_domain }}' --deploy-hook "systemctl restart coturn" creates='/etc/letsencrypt/live/{{ coturn_domain }}/fullchain.pem'

- name: configure coturn
  template:
    src: turnserver.conf.j2
    dest: /etc/turnserver.conf
  notify: restart coturn

- name: enable logrotate for coturn
  template:
    src: logrotate
    dest: /etc/logrotate.d/coturn

- name: enable coturn server in defaults
  lineinfile:
    path: /etc/default/coturn
    regexp: 'TURNSERVER_ENABLED'
    line: 'TURNSERVER_ENABLED=1'

- name: start and enable coturn
  systemd:
    name: coturn
    enabled: true
    state: started
